/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println(scanForSemicolons("src/main/resources/gates.js"));
    }

    public static String scanForSemicolons (String path) {
        String errors = "";
        try {
            Scanner linter;
            linter = new Scanner(new File(path));
            int lineCounter = 1;

            while (linter.hasNextLine()) {
                String currentLine = linter.nextLine();
                if (currentLine.endsWith("{") || currentLine.endsWith(";") || currentLine.startsWith("if")) {
                    lineCounter++;
                    errors += String.format("Line %d is missing a semicolon", lineCounter) + "\n";
                } else {
                    linter.nextLine();
                    lineCounter++;
                }
            }

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return errors;
    }
}
