/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int n) {
        int[] rollArray = new int[n];

        for (int i = 0; i < n; i++) {
            rollArray[i] = (int) (Math.random() * 6) + 1;
        }
        return rollArray;
    }

    public static boolean containsDuplicates(int[] array) {
        boolean checkDuplicate = false;

        for (int i = 0; i < array.length; i++) {
            for (int k = 0; k < array.length; k++) {
                if (array[i] == array[k] && i != k) {
                    checkDuplicate = true;
                }
            }
        }
        return checkDuplicate;
    }

    public static double calculateSingleArrayAverages(int[] array) {
        double total = 0;
        double average = 0;

        for (int value : array) {
            total = total + value;
        }

        average = total / array.length;

        return average;
    }

    public static int[] findArrayWithLowestAverage(int[][] array) {
        int[] lowestAverageArray = array[0];
        double currentLowestAverage = calculateSingleArrayAverages(array[0]);

        for (int[] ints : array) {
            double checkingAverage = calculateSingleArrayAverages(ints);

            if (currentLowestAverage > checkingAverage) {
                currentLowestAverage = checkingAverage;
                lowestAverageArray = ints;
            }
        }
        return lowestAverageArray;
    }
}