/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll (int n) {
        int[] rollArray = new int[n];

        for (int i = 0; i < n; i++) {
            rollArray[i] = (int) (Math.random() * 6) + 1;
        }
        return rollArray;
    }

    public static boolean containsDuplicates (int[] array) {
        boolean checkDuplicate = false;

        for (int i = 0; i < array.length; i++) {
            for (int k = 0; k < array.length; k++) {
                if (array[i] == array[k] && i != k) {
                    checkDuplicate = true;
                }
            }
        }
        return checkDuplicate;
    }

    public static float calculateSingleArrayAverages (int[] array) {
        int total = 0;
        int average = 0;

        for (int i = 0; i < array.length; i++) {
            total = total + array[i];
        }

        average = total/array.length;

        return average;
    }
}
